<a href="https://colab.research.google.com/github/DavidSchneider47/ALIrecommendation/blob/main/Stations_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd

In [20]:
#run the code to import a file from my local directory into Google Colab
from google.colab import files
uploaded = files.upload()

Saving Stations.csv to Stations (1).csv

In [21]:
#define the file as df
df= pd.read_csv('Stations.csv')

Exploratory Data Analysis

In [22]:
#display the column headings and the first few rows
df.head()

,NTD ID,Agency Name,Reporter Type,Reporting Module,Primary Mode Served,Secondary Modes Served,Facility ID,Facility Type,Facility Name,Street Address,...,Section of a Larger Facility,Year Built or Reconstructed as New,Percent Agency Capital Responsibility,Cross Agency Facility Flag,Condition Assessment Date,Condition Assessment,Separate Asset Flag,Notes,AddressComplete,ReverseAddress
0,1,King County Department of Metro Transit,Full Reporter,Urban,Bus,NaN,19124.0,Underground Fixed Guideway Station,International District Station,5Th Avenue South & South Jackson St.,...,0.0,2007.0,100.0,N,12/31/2019,3.0,N,NaN,"5Th Avenue South & South Jackson St., Seattle,...",NaN
1,1,King County Department of Metro Transit,Full Reporter,Urban,Bus,NaN,19125.0,Underground Fixed Guideway Station,Pioneer Square Station,3Rd Avenue & James Street,...,0.0,2007.0,100.0,N,12/31/2019,3.0,N,NaN,"3Rd Avenue & James Street, Seattle, WA, 98104",NaN
2,1,King County Department of Metro Transit,Full Reporter,Urban,Bus,NaN,19126.0,Underground Fixed Guideway Station,Westlake Station,4Th Avenue & Pine Street,...,0.0,2009.0,100.0,N,12/31/2019,3.0,N,NaN,"4Th Avenue & Pine Street, Seattle, WA, 98101",NaN
3,1,King County Department of Metro Transit,Full Reporter,Urban,Bus,NaN,19127.0,Underground Fixed Guideway Station,University Street Station,3Rd Avenue & Seneca Street,...,0.0,2009.0,100.0,N,12/31/2019,3.0,N,NaN,"3Rd Avenue & Seneca Street, Seattle, WA, 98101",NaN
4,1,King County Department of Metro Transit,Full Reporter,Urban,Bus,NaN,19141.0,Underground Fixed Guideway Station,Capitol Hill Light Rail Station,140 Broadway E,...,0.0,2016.0,0.0,N,NaN,NaN,N,NaN,"140 Broadway E, Seattle, WA, 98102",NaN

In [23]:
#identify the number of rows and columns
df.shape

(4479, 31)

In [24]:
#identify the data types
# it would be good to make some data conversions in some of these items. We'll come back to this
df.dtypes

NTD ID                                       object
Agency Name                                  object
Reporter Type                                object
Reporting Module                             object
Primary Mode Served                          object
Secondary Modes Served                       object
Facility ID                                 float64
Facility Type                                object
Facility Name                                object
Street Address                               object
City                                         object
State                                        object
ZIP Code                                    float64
Latitude                                    float64
Longitude                                   float64
Non-Agency Mode Served                       object
Private Modes Served                         object
Administrative/Maintenance Facility Flag    float64
Passenger/Parking Facility Flag             float64
Square Feet                                 float64
Number of Parking Spaces                    float64
Section of a Larger Facility                float64
Year Built or Reconstructed as New          float64
Percent Agency Capital Responsibility       float64
Cross Agency Facility Flag                   object
Condition Assessment Date                    object
Condition Assessment                        float64
Separate Asset Flag                          object
Notes                                        object
AddressComplete                              object
ReverseAddress                               object
dtype: object

In [25]:
#check for null values. Strange, I didn't think there were any nulls for "NTD ID" and some other categories
df.isnull().sum()

NTD ID                                        15
Agency Name                                   15
Reporter Type                                 15
Reporting Module                              15
Primary Mode Served                           15
Secondary Modes Served                      3958
Facility ID                                   15
Facility Type                                 15
Facility Name                                 15
Street Address                               913
City                                         814
State                                        821
ZIP Code                                     839
Latitude                                      68
Longitude                                     68
Non-Agency Mode Served                      4474
Private Modes Served                        4390
Administrative/Maintenance Facility Flag      15
Passenger/Parking Facility Flag               15
Square Feet                                   19
Number of Parking Spaces                    4475
Section of a Larger Facility                  15
Year Built or Reconstructed as New            15
Percent Agency Capital Responsibility         15
Cross Agency Facility Flag                    15
Condition Assessment Date                    697
Condition Assessment                         697
Separate Asset Flag                           15
Notes                                       2876
AddressComplete                               15
ReverseAddress                              3649
dtype: int64

In [26]:
#identify the rows with a null value for NTD ID
filtered_rows = df[df['NTD ID'].isnull()]

In [9]:
#created a data frame for these rows
filtered_rows.to_csv('filtered_rows.csv')

In [10]:
#xported the rows for further inspection. It looks like the file picked up a few blank rows from the .csv in my local directory. OK to delte
from google.colab import files
files.download('filtered_rows.csv')

Eliminate Null Values

In [27]:
#delete the rows where "NTD_ID" is null
df = df.dropna(subset=['NTD ID'])

In [28]:
#check for the new data frame
df.shape

(4464, 31)

In [29]:
#check again for fields with null values. Good that "AddressComplete" has no null values
#however, it would be good to populate the missing lon/lat values and some other info. We'll come back to this
df.isnull().sum()

NTD ID                                         0
Agency Name                                    0
Reporter Type                                  0
Reporting Module                               0
Primary Mode Served                            0
Secondary Modes Served                      3943
Facility ID                                    0
Facility Type                                  0
Facility Name                                  0
Street Address                               898
City                                         799
State                                        806
ZIP Code                                     824
Latitude                                      53
Longitude                                     53
Non-Agency Mode Served                      4459
Private Modes Served                        4375
Administrative/Maintenance Facility Flag       0
Passenger/Parking Facility Flag                0
Square Feet                                    4
Number of Parking Spaces                    4460
Section of a Larger Facility                   0
Year Built or Reconstructed as New             0
Percent Agency Capital Responsibility          0
Cross Agency Facility Flag                     0
Condition Assessment Date                    682
Condition Assessment                         682
Separate Asset Flag                            0
Notes                                       2861
AddressComplete                                0
ReverseAddress                              3634
dtype: int64

Address Duplicate Data

In [30]:
#check the dataframe for entire row duplicates. Lpoks iike no entirely duplicated rows
df.duplicated().sum()

0

In [31]:
#check to see if there are any stations with the exact same lon/lat coordinates
duplicates = df[df.duplicated(subset=['Longitude', 'Latitude'], keep=False)]

In [15]:
#convert these to a .csv
duplicates.to_csv('duplicates.csv')

In [32]:
#identify the number of rows that include duplicates.
# assuming one duplicate row per original row, that's 399 duplicate rows to drop.
duplicates.shape

(797, 31)

In [ ]:
#download the file for a closer inspection
#offline inspection reveals that some transit stations are served by multiple modes
#we will consider the heavy rail, light rail, and streetcar rail modes to be the primary modes in these cases.
files.download('duplicates.csv')

In [33]:
# Identify rows where 'Primary Mode Served' contains one of the specified terms
specified_terms = ['Bus', 'Commuter Bus', 'Maglev', 'Streetcar Rail']
filtered_rows = df[df['Primary Mode Served'].isin(specified_terms)]

In [34]:
# Drop the duplicates from the dataset based on the terms specified in 'Primary Mode Served'
df = df.drop(filtered_rows.index)

# Show the shape of the original and new DataFrame for comparison
original_shape = df.shape
new_shape = df.shape

original_shape, new_shape

((3698, 31), (3698, 31))

In [35]:
#check again to see if there are any stations with the exact same lon/lat coordinates
duplicates = df[df.duplicated(subset=['Longitude', 'Latitude'], keep=False)]

In [36]:
#now we are down to 341 duplicates from 797
duplicates.shape

(341, 31)

In [37]:
#and the dataset is down to 3,698 unique rows
df.shape

(3698, 31)

In [38]:
#another source of duplicates is that there are northbound and southbound sides of the same station labeled with different facility ide
# Initialize an empty DataFrame to store rows where differences in 'Facility ID' are found
differences_facility_id_df = pd.DataFrame()
# Identify rows with duplicate 'Latitude' and 'Longitude'
duplicates = df[df.duplicated(subset=['Latitude', 'Longitude'], keep=False)].sort_values(by=['Latitude', 'Longitude'])
# Group by 'Latitude' and 'Longitude' and iterate through each group to find differences in 'Facility ID'
for _, group in duplicates.groupby(['Latitude', 'Longitude']):
    # Take the first row's 'Facility ID' as reference
    reference_facility_id = group.iloc[0]['Facility ID']
    # Iterate through each row to find differences in 'Facility ID' with the reference row
    for index, row in group.iloc[1:].iterrows():
        # Check if 'Facility ID' is different
        if row['Facility ID'] != reference_facility_id:
            # Add the index of the row to the 'differences_facility_id_df'
            differences_facility_id_df = differences_facility_id_df.append(
                {'Index': index, 'Different Facility ID': row['Facility ID']}, ignore_index=True
            )

<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(
<ipython-input-38-22d73dee7251>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  differences_facility_id_df = differences_facility_id_df.append(

In [39]:
# Drop one of the duplicate rows where 'Facility ID' is different
# We'll drop the first occurrence and keep the subsequent ones
df = df.drop(differences_facility_id_df['Index'].astype(int))

In [40]:
#check the resulting data frame to see fewer rows overall
df.shape

(3542, 31)

In [41]:
#check to see if there are any stations with the exact same lon/lat coordinates
duplicates = df[df.duplicated(subset=['Longitude', 'Latitude'], keep=False)]

In [42]:
#now we are down to only 53 duplicates and these happen to be the 53 rows with blank lon/lat coordinates that we will fix later.
duplicates.shape

(53, 31)

In [43]:
df.isnull().sum()

NTD ID                                         0
Agency Name                                    0
Reporter Type                                  0
Reporting Module                               0
Primary Mode Served                            0
Secondary Modes Served                      3078
Facility ID                                    0
Facility Type                                  0
Facility Name                                  0
Street Address                               728
City                                         722
State                                        726
ZIP Code                                     722
Latitude                                      53
Longitude                                     53
Non-Agency Mode Served                      3537
Private Modes Served                        3469
Administrative/Maintenance Facility Flag       0
Passenger/Parking Facility Flag                0
Square Feet                                    0
Number of Parking Spaces                    3542
Section of a Larger Facility                   0
Year Built or Reconstructed as New             0
Percent Agency Capital Responsibility          0
Cross Agency Facility Flag                     0
Condition Assessment Date                    328
Condition Assessment                         328
Separate Asset Flag                            0
Notes                                       2254
AddressComplete                                0
ReverseAddress                              2814
dtype: int64

In [ ]:
#download the resulting file for further inspection
df.to_csv("stations_clean.csv")

In [ ]:
files.download("stations_clean.csv")

Populate Missing City, State, and ZIP Code data from the AddressComplete Column

In [44]:
#run a complex code to populate most of the blank city, state, zip code cells from the "AddressComplete" data
import re

# Define function to extract city, state and zip from AddressComplete column
def extract_info(address):
    # Regular expression patterns to extract city, state and zip
    city_pattern = r"(?<=, )([^,]+)(?=, [A-Z]{2},)"
    state_pattern = r", ([A-Z]{2}),"
    zip_pattern = r"(\d{5})$"

    city = re.search(city_pattern, address)
    state = re.search(state_pattern, address)
    zip_code = re.search(zip_pattern, address)

    return city.group(0) if city else None, state.group(1) if state else None, zip_code.group(0) if zip_code else None

# Apply the function to extract city, state and zip
df["ExtractedCity"], df["ExtractedState"], df["ExtractedZip"] = zip(*df["AddressComplete"].apply(extract_info))

# If City, State, or Zip Code columns are empty, fill them with the extracted values
df["City"] = df["City"].where(df["City"].notnull(), df["ExtractedCity"])
df["State"] = df["State"].where(df["State"].notnull(), df["ExtractedState"])
df["ZIP Code"] = df["ZIP Code"].where(df["ZIP Code"].notnull(), df["ExtractedZip"])

# Drop the temporary extracted columns
df = df.drop(columns=["ExtractedCity", "ExtractedState", "ExtractedZip"])

# Display the updated dataframe
df[["AddressComplete", "City", "State", "ZIP Code"]].head()

                                      AddressComplete      City State ZIP Code
17         2599 N Interstate Ave, Portland, OR, 97227  Portland    OR  97227.0
18            Sw 5Th & Jefferson, Portland, OR, 97204  Portland    OR  97204.0
19  Ne Holladay St/Martin Luther King Jr Blvd, Por...  Portland    OR  97232.0
20        E Burnside & 102Nd Ave, Portland, OR, 97216  Portland    OR  97216.0
26     Sw Morrison St & 10Th Ave, Portland, OR, 97205  Portland    OR  97205.0

In [45]:
#test to see if there are some missing information--it looks like there are still 722 zip codesl missing
df.isnull().sum()

NTD ID                                         0
Agency Name                                    0
Reporter Type                                  0
Reporting Module                               0
Primary Mode Served                            0
Secondary Modes Served                      3078
Facility ID                                    0
Facility Type                                  0
Facility Name                                  0
Street Address                               728
City                                           0
State                                          0
ZIP Code                                     722
Latitude                                      53
Longitude                                     53
Non-Agency Mode Served                      3537
Private Modes Served                        3469
Administrative/Maintenance Facility Flag       0
Passenger/Parking Facility Flag                0
Square Feet                                    0
Number of Parking Spaces                    3542
Section of a Larger Facility                   0
Year Built or Reconstructed as New             0
Percent Agency Capital Responsibility          0
Cross Agency Facility Flag                     0
Condition Assessment Date                    328
Condition Assessment                         328
Separate Asset Flag                            0
Notes                                       2254
AddressComplete                                0
ReverseAddress                              2814
dtype: int64

In [ ]:
#download the resulting file for further inspection
df.to_csv("stations_clean1.csv")

In [ ]:
files.download("stations_clean1.csv")

In [46]:
#run additional code to extract additional city, state, zip informatiion from the Reverse Address Column
# Redefine the function to extract city, state and zip
def extract_info(address):
    # Regular expression patterns to extract city, state and zip
    city_pattern = r"(?<=, )([^,]+)(?=, [A-Z]{2},)"
    state_pattern = r", ([A-Z]{2}),"
    zip_pattern = r"(\d{5})$"

    city = re.search(city_pattern, str(address))
    state = re.search(state_pattern, str(address))
    zip_code = re.search(zip_pattern, str(address))

    return city.group(0) if city else None, state.group(1) if state else None, zip_code.group(0) if zip_code else None

# Extract city, state, and zip from ReverseAddress column for rows with missing values
rows_with_missing_values = df[df["City"].isnull() | df["State"].isnull() | df["ZIP Code"].isnull()]

# Apply the extraction function to these rows
rows_with_missing_values[["City", "State", "ZIP Code"]] = rows_with_missing_values["ReverseAddress"].apply(extract_info).apply(pd.Series)

# Update the original dataframe
df.update(rows_with_missing_values)

# Display the updated dataframe with previously missing values
df[["ReverseAddress", "City", "State", "ZIP Code"]].head()

<ipython-input-46-1983709f9796>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rows_with_missing_values[["City", "State", "ZIP Code"]] = rows_with_missing_values["ReverseAddress"].apply(extract_info).apply(pd.Series)

   ReverseAddress      City State ZIP Code
17            NaN  Portland    OR  97227.0
18            NaN  Portland    OR  97204.0
19            NaN  Portland    OR  97232.0
20            NaN  Portland    OR  97216.0
26            NaN  Portland    OR  97205.0

In [47]:
#It looks like this code has not worked
df.isnull().sum()

NTD ID                                         0
Agency Name                                    0
Reporter Type                                  0
Reporting Module                               0
Primary Mode Served                            0
Secondary Modes Served                      3078
Facility ID                                    0
Facility Type                                  0
Facility Name                                  0
Street Address                               728
City                                           0
State                                          0
ZIP Code                                     722
Latitude                                      53
Longitude                                     53
Non-Agency Mode Served                      3537
Private Modes Served                        3469
Administrative/Maintenance Facility Flag       0
Passenger/Parking Facility Flag                0
Square Feet                                    0
Number of Parking Spaces                    3542
Section of a Larger Facility                   0
Year Built or Reconstructed as New             0
Percent Agency Capital Responsibility          0
Cross Agency Facility Flag                     0
Condition Assessment Date                    328
Condition Assessment                         328
Separate Asset Flag                            0
Notes                                       2254
AddressComplete                                0
ReverseAddress                              2814
dtype: int64

In [48]:
# Inspect the rows with blank ZIP Codes
blank_zip_codes = df[df["ZIP Code"].isnull()]

blank_zip_codes[["AddressComplete", "ReverseAddress", "City", "State", "ZIP Code"]]

,AddressComplete,ReverseAddress,City,State,ZIP Code
1634,"NA, NA, NA, NA","2274 31st St, Astoria, NY 11105, USA",NA,NA,None
1635,"NA, NA, NA, NA","9022 Hoyt Ave S, Queens, NY 11102, USA",NA,NA,None
1636,"NA, NA, NA, NA","30 Av, 30th Ave, Queens, NY 11102, USA",NA,NA,None
1637,"NA, NA, NA, NA","Broadway, Queens, NY 11106, USA",NA,NA,None
1638,"NA, NA, NA, NA","31 St/36 Av, Queens, NY 11106, USA",NA,NA,None
...,...,...,...,...,...
2535,"NA, NA, NA, NA","Parkview Station, Upper Darby, PA 19082, USA",NA,NA,None
2536,"NA, NA, NA, NA","Township Line Road Station, Haverford Township...",NA,NA,None
2537,"NA, NA, NA, NA","26-64 Crest Terrace, Norristown, PA 19401, USA",NA,NA,None
2538,"NA, NA, NA, NA","69th Street Transportation Center, 6901 Market...",NA,NA,None
3145,"NA, NA, NA, NA","Gary/Chicago Airport, Gary, IN 46406, USA",NA,NA,None

In [49]:
# Define a function to extract ZIP code from a given address string
def extract_zip_from_address(address):
    zip_pattern = r"(\d{5})$"
    zip_code = re.search(zip_pattern, str(address))
    return zip_code.group(0) if zip_code else None

# For rows with blank ZIP codes, try extracting ZIP code from AddressComplete and then from ReverseAddress
blank_zip_codes["ZIP Code"] = blank_zip_codes["AddressComplete"].apply(extract_zip_from_address).fillna(
    blank_zip_codes["ReverseAddress"].apply(extract_zip_from_address))

# Update the original dataframe
df.update(blank_zip_codes)

# Check if there are still any blank ZIP Codes after the update
remaining_blank_zip_codes = df[df["ZIP Code"].isnull()]

remaining_blank_zip_codes[["AddressComplete", "ReverseAddress", "City", "State", "ZIP Code"]]

<ipython-input-49-f9e988bca696>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  blank_zip_codes["ZIP Code"] = blank_zip_codes["AddressComplete"].apply(extract_zip_from_address).fillna(

,AddressComplete,ReverseAddress,City,State,ZIP Code
1634,"NA, NA, NA, NA","2274 31st St, Astoria, NY 11105, USA",NA,NA,None
1635,"NA, NA, NA, NA","9022 Hoyt Ave S, Queens, NY 11102, USA",NA,NA,None
1636,"NA, NA, NA, NA","30 Av, 30th Ave, Queens, NY 11102, USA",NA,NA,None
1637,"NA, NA, NA, NA","Broadway, Queens, NY 11106, USA",NA,NA,None
1638,"NA, NA, NA, NA","31 St/36 Av, Queens, NY 11106, USA",NA,NA,None
...,...,...,...,...,...
2535,"NA, NA, NA, NA","Parkview Station, Upper Darby, PA 19082, USA",NA,NA,None
2536,"NA, NA, NA, NA","Township Line Road Station, Haverford Township...",NA,NA,None
2537,"NA, NA, NA, NA","26-64 Crest Terrace, Norristown, PA 19401, USA",NA,NA,None
2538,"NA, NA, NA, NA","69th Street Transportation Center, 6901 Market...",NA,NA,None
3145,"NA, NA, NA, NA","Gary/Chicago Airport, Gary, IN 46406, USA",NA,NA,None

In [50]:
# Display a sample of addresses from rows with missing ZIP codes
sample_addresses = remaining_blank_zip_codes[["AddressComplete", "ReverseAddress"]].sample(20)
sample_addresses

     AddressComplete                                     ReverseAddress
2072  NA, NA, NA, NA     W 116 St/Malcolm X Bl, New York, NY 10026, USA
1852  NA, NA, NA, NA  2937 Frederick Douglass Blvd, New York, NY 100...
2057  NA, NA, NA, NA            1978 Birchall Ave, Bronx, NY 10462, USA
1695  NA, NA, NA, NA        55 Street, 55th St, Brooklyn, NY 11219, USA
1725  NA, NA, NA, NA             1955 Broadway, Brooklyn, NY 11207, USA
1668  NA, NA, NA, NA              5907 4th Ave, Brooklyn, NY 11220, USA
1688  NA, NA, NA, NA            Brighton Beach, Brooklyn, NY 11235, USA
1803  NA, NA, NA, NA              45 Church St, New York, NY 10007, USA
1907  NA, NA, NA, NA    875 3rd Ave 23rd Floor, New York, NY 10022, USA
2101  NA, NA, NA, NA       E 42 St/Madison Ave, New York, NY 10165, USA
1829  NA, NA, NA, NA       Aqueduct-N Conduit Av, Queens, NY 11417, USA
1715  NA, NA, NA, NA                      104 St, Queens, NY 11418, USA
2352  NA, NA, NA, NA  Germantown, District of Freedom#8573311~!#, Ph...
1634  NA, NA, NA, NA               2274 31st St, Astoria, NY 11105, USA
1783  NA, NA, NA, NA                    145 St, New York, NY 10031, USA
2366  NA, NA, NA, NA  Elm Street, 793 Markley St, Norristown, PA 194...
2501  NA, NA, NA, NA  Cecil B. Moore Station, Philadelphia, PA 19122...
1793  NA, NA, NA, NA          101 Columbus Cir, New York, NY 10019, USA
2097  NA, NA, NA, NA  42 Street & Lexington Avenue, New York, NY 101...
2520  NA, NA, NA, NA  Gulph Mills Station, Upper Merion Township, PA...

In [51]:
# Extract ZIP codes from the ReverseAddress column for the remaining rows
remaining_blank_zip_codes["ZIP Code"] = remaining_blank_zip_codes["ReverseAddress"].apply(extract_zip_from_address)

# Update the original dataframe
df.update(remaining_blank_zip_codes)

# Check again if there are still any blank ZIP Codes after the update
final_remaining_blank_zip_codes = df[df["ZIP Code"].isnull()]

final_remaining_blank_zip_codes[["AddressComplete", "ReverseAddress", "City", "State", "ZIP Code"]]

<ipython-input-51-6636347a1baf>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  remaining_blank_zip_codes["ZIP Code"] = remaining_blank_zip_codes["ReverseAddress"].apply(extract_zip_from_address)

,AddressComplete,ReverseAddress,City,State,ZIP Code
1634,"NA, NA, NA, NA","2274 31st St, Astoria, NY 11105, USA",NA,NA,None
1635,"NA, NA, NA, NA","9022 Hoyt Ave S, Queens, NY 11102, USA",NA,NA,None
1636,"NA, NA, NA, NA","30 Av, 30th Ave, Queens, NY 11102, USA",NA,NA,None
1637,"NA, NA, NA, NA","Broadway, Queens, NY 11106, USA",NA,NA,None
1638,"NA, NA, NA, NA","31 St/36 Av, Queens, NY 11106, USA",NA,NA,None
...,...,...,...,...,...
2535,"NA, NA, NA, NA","Parkview Station, Upper Darby, PA 19082, USA",NA,NA,None
2536,"NA, NA, NA, NA","Township Line Road Station, Haverford Township...",NA,NA,None
2537,"NA, NA, NA, NA","26-64 Crest Terrace, Norristown, PA 19401, USA",NA,NA,None
2538,"NA, NA, NA, NA","69th Street Transportation Center, 6901 Market...",NA,NA,None
3145,"NA, NA, NA, NA","Gary/Chicago Airport, Gary, IN 46406, USA",NA,NA,None

In [52]:
# Redefine the ZIP code extraction function to be more flexible
def flexible_extract_zip_from_address(address):
    zip_pattern = r"(\d{5})"
    zip_code = re.search(zip_pattern, str(address))
    return zip_code.group(0) if zip_code else None

# Directly update the ZIP Code column for the rows with missing ZIP codes using the more flexible method
df.loc[remaining_blank_zip_codes.index, "ZIP Code"] = remaining_blank_zip_codes["ReverseAddress"].apply(flexible_extract_zip_from_address)

# Check again if there are still any blank ZIP Codes after the update
final_remaining_blank_zip_codes = df[df["ZIP Code"].isnull()]

final_remaining_blank_zip_codes[["AddressComplete", "ReverseAddress", "City", "State", "ZIP Code"]]

,AddressComplete,ReverseAddress,City,State,ZIP Code
1776,"NA, NA, NA, NA","Broadway/Dyckman St, New York, NY, USA",New York,NY,None
1846,"NA, NA, NA, NA","Grand Concourse/E 182 St, Bronx, NY, USA",Bronx,NY,None
1928,"NA, NA, NA, NA","Broadway/w 225 St, New York, NY, USA",New York,NY,None
2004,"NA, NA, NA, NA","Longwood Av, Bronx, NY, USA",Bronx,NY,None
2010,"NA, NA, NA, NA","Woodlawn, Bronx, NY, USA",Bronx,NY,None
2043,"NA, NA, NA, NA","Brooklyn Bridge - City Hall, New York, NY, USA",New York,NY,None
2070,"NA, NA, NA, NA","W 135 St/Malcolm X Bl, New York, NY, USA",New York,NY,None
2502,"NA, NA, NA, NA","Girard Av & Broad St, Philadelphia, PA, USA",Philadelphia,PA,None
2521,"NA, NA, NA, NA","8th and Market, Philadelphia, PA, USA",Philadelphia,PA,None

In [53]:
#now we are down to a more manageable 9 records with no zip codes!
df.isnull().sum()

NTD ID                                         0
Agency Name                                    0
Reporter Type                                  0
Reporting Module                               0
Primary Mode Served                            0
Secondary Modes Served                      3078
Facility ID                                    0
Facility Type                                  0
Facility Name                                  0
Street Address                               728
City                                           0
State                                          0
ZIP Code                                       9
Latitude                                      53
Longitude                                     53
Non-Agency Mode Served                      3537
Private Modes Served                        3469
Administrative/Maintenance Facility Flag       0
Passenger/Parking Facility Flag                0
Square Feet                                    0
Number of Parking Spaces                    3542
Section of a Larger Facility                   0
Year Built or Reconstructed as New             0
Percent Agency Capital Responsibility          0
Cross Agency Facility Flag                     0
Condition Assessment Date                    328
Condition Assessment                         328
Separate Asset Flag                            0
Notes                                       2254
AddressComplete                                0
ReverseAddress                              2814
dtype: int64

In [ ]:
#download the file for further inspection
df.to_csv("stations_clean2.csv")

In [ ]:
#download the file for further inspection
files.download("stations_clean2.csv")

Populate Missing Lon/Lat Data

In [60]:
#Now let's see if we can find lon/lat coordinates for the 53 rows with missing coordiantes but an addressing
!pip install googlemaps

Collecting googlemaps
  Downloading googlemaps-4.10.0.tar.gz (33 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests<3.0,>=2.20.0 in /usr/local/lib/python3.10/dist-packages (from googlemaps) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (2023.7.22)
Building wheels for collected packages: googlemaps
  Building wheel for googlemaps (setup.py) ... done
  Created wheel for googlemaps: filename=googlemaps-4.10.0-py3-none-any.whl size=40713 sha256=3b576a2c00150cae19429d8e6d49005b9c236618638fdd957318a31c62e783ba
  Stored in directory: /root/.cache/pip/wheels/17/f8/79/999d5d37118fd35d7219ef57933eb9d09886c4c4503a800f84
Successfully built googlemaps
Installing collected packages: googlemaps
Successfully installed googlemaps-4.10.0

In [61]:
import googlemaps

In [62]:
def geocode_addresses(api_key, addresses):
    gmaps = googlemaps.Client(key=api_key)
    lat_lon_results = {}

    for address in addresses:
        result = gmaps.geocode(address)
        if result and len(result) > 0:
            location = result[0]['geometry']['location']
            lat_lon_results[address] = (location['lat'], location['lng'])
        else:
            lat_lon_results[address] = (None, None)

    return lat_lon_results

In [67]:
api_key="AIzaSyBnqCaL5Nn8hGkDfgwDIwMUjsirRG-18L0"

In [ ]:
"#Let's drop some fields that we are not going to use from the dataset.
df = df.drop(['Secondary Modes Served', 'Street Address','Non-Agency Mode Served','Private Modes Served','Number of Parking Spaces','Notes'], axis=1)

In [82]:
addresses_to_geocode = ["Sw 5Th & Jefferson, Portland, OR, 97204",
    "Sw 18Th Ave & Jefferson St, Portland, OR, 97201",
    "Nw 5Th & Couch, Portland, OR, 97209",
    "Sw 5Th & Jackson, Portland, OR, 97201",
    "Sw 6Th & College, Portland, OR, 97201",
    "Sw 5Th & Mill, Portland, OR, 97201",
    "Sw 6Th & Montgomery, Portland, OR, 97201",
    "Sw 5Th & Oak, Portland, OR, 97204",
    "Sw 6Th & Madison, Portland, OR, 97204",
    "Sw 6Th & Pine, Portland, OR, 97204",
    "Nw 5Th & Glisan, Portland, OR, 97209",
    "Sw 18Th Ave & Salmon St, Portland, OR, 97205",
    "Main St. & Atlantic Ave., Matawan, NJ, 07747",
    "Railroad Plz Shore Rd. & Ohio Ave., Absecon, NJ, 08205",
    "Main St. & Corlies Ave., Allenhurst, NJ, 07711",
    "Bay & Pine St., Montclair, NJ, 07042",
    "Main St. & Rt. 202, Boonton, NJ, 07005",
    "S. Harrison Ave & Prospect St., East Orange, NJ, 07018",
    "East Main St. & Cole Drive, Bridgewater, NJ, 08807",
    "Front St. Between Fairmount & Washington Ave., Chatham, NJ, 07928",
    "Valley Rd. & Long Hill Rd., Gillette, NJ, 07933",
    "Broadway & Hillsdale Ave., Hillsdale, NJ, 07642",
    "Brookside Ave. & 1St St., Ho-Ho-Kus, NJ, 07450",
    "Main St. & Comly Rd., Lincoln Park, NJ, 07035",
    "3Rd Ave. Between North Bath Ave. & Morris Ave., Long Branch, NJ, 07740",
    "Main Street & Woodbridge Ave, Metuchen, NJ, 08837",
    "Division Ave. Between Oaks Rd. & Valley Rd., Millington, NJ, 07946",
    "Rt. 80 & Howard Blvd, Mt. Arlington, NJ, 07856",
    "Station Rd & Rt. 53, Denville, NJ, 07834",
    "Main St. & Rt. 46, Netcong, NJ, 07857",
    "25 University Ave (Broad St. & University Pl), Newark, NJ, 07102",
    "Elm St. Between Smith St. & Market St., Perth Amboy, NJ, 08861",
    "County Rd & County Ave, Secaucus, NJ, 07094",
    "S. Bridge & Veterans Memorial Dr. W, Somerville, NJ, 08876",
    "Central Ave. & Main St., Stirling, NJ, 07980",
    "Prospect & Hewson Aves., Waldwick, NJ, 07463",
    "Broadway & Westwood Ave., Westwood, NJ, 07675",
    "Broadway & Woodcliff Ave., Woodcliff, NJ, 07677",
    "34Th & Ave E, Bayonne, NJ, 07002",
    "45Th & Ave E, Bayonne, NJ, 07002",
    "Between Hudson & Greene St., Jersey City, NJ, 07302",
    "East Of Greene St. Between Morgan & Steuben Sts., Jersey City, NJ, 07302"]

In [85]:
# Get geocoded results
results = geocode_addresses(api_key, addresses_to_geocode)

In [87]:
# Populate the DataFrame
for index, row in df.iterrows():
    if pd.isnull(row['Latitude']) and pd.isnull(row['Longitude']):
        address = row['AddressComplete']
        if address in results:
            lat, lon = results[address]
            df.at[index, 'Latitude'] = lat
            df.at[index, 'Longitude'] = lon

In [88]:
#let's re-check for missing lons and lats. None!
df.isnull().sum()

NTD ID                                         0
Agency Name                                    0
Reporter Type                                  0
Reporting Module                               0
Primary Mode Served                            0
Secondary Modes Served                      3078
Facility ID                                    0
Facility Type                                  0
Facility Name                                  0
Street Address                               728
City                                           0
State                                          0
ZIP Code                                       9
Latitude                                       0
Longitude                                      0
Non-Agency Mode Served                      3537
Private Modes Served                        3469
Administrative/Maintenance Facility Flag       0
Passenger/Parking Facility Flag                0
Square Feet                                    0
Number of Parking Spaces                    3542
Section of a Larger Facility                   0
Year Built or Reconstructed as New             0
Percent Agency Capital Responsibility          0
Cross Agency Facility Flag                     0
Condition Assessment Date                    328
Condition Assessment                         328
Separate Asset Flag                            0
Notes                                       2254
AddressComplete                                0
ReverseAddress                              2814
dtype: int64

Convert a few datatypes into Objects

In [89]:
#Lets check the resulting structure
df.shape

(3542, 31)

In [90]:
#now most of the columns in thr dataset have no missing values
df.isnull().sum()

NTD ID                                         0
Agency Name                                    0
Reporter Type                                  0
Reporting Module                               0
Primary Mode Served                            0
Secondary Modes Served                      3078
Facility ID                                    0
Facility Type                                  0
Facility Name                                  0
Street Address                               728
City                                           0
State                                          0
ZIP Code                                       9
Latitude                                       0
Longitude                                      0
Non-Agency Mode Served                      3537
Private Modes Served                        3469
Administrative/Maintenance Facility Flag       0
Passenger/Parking Facility Flag                0
Square Feet                                    0
Number of Parking Spaces                    3542
Section of a Larger Facility                   0
Year Built or Reconstructed as New             0
Percent Agency Capital Responsibility          0
Cross Agency Facility Flag                     0
Condition Assessment Date                    328
Condition Assessment                         328
Separate Asset Flag                            0
Notes                                       2254
AddressComplete                                0
ReverseAddress                              2814
dtype: int64

In [91]:
#convert zip code from a float to an object
df['ZIP Code'] = df['ZIP Code'].astype('str')

In [92]:
#convert Year Built from a float to an object
df['Year Built or Reconstructed as New'] = df['Year Built or Reconstructed as New'].astype('str')

In [93]:
#check the results
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3542 entries, 17 to 4463
Data columns (total 31 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   NTD ID                                    3542 non-null   object
 1   Agency Name                               3542 non-null   object
 2   Reporter Type                             3542 non-null   object
 3   Reporting Module                          3542 non-null   object
 4   Primary Mode Served                       3542 non-null   object
 5   Secondary Modes Served                    464 non-null    object
 6   Facility ID                               3542 non-null   float64
 7   Facility Type                             3542 non-null   object
 8   Facility Name                             3542 non-null   object
 9   Street Address                            2814 non-null   object
 10  City                                      3542 non-null   object
 11  State                                     3542 non-null   object
 12  ZIP Code                                  3542 non-null   object
 13  Latitude                                  3542 non-null   float64
 14  Longitude                                 3542 non-null   float64
 15  Non-Agency Mode Served                    5 non-null      object
 16  Private Modes Served                      73 non-null     object
 17  Administrative/Maintenance Facility Flag  3542 non-null   float64
 18  Passenger/Parking Facility Flag           3542 non-null   float64
 19  Square Feet                               3542 non-null   float64
 20  Number of Parking Spaces                  0 non-null      float64
 21  Section of a Larger Facility              3542 non-null   float64
 22  Year Built or Reconstructed as New        3542 non-null   object
 23  Percent Agency Capital Responsibility     3542 non-null   float64
 24  Cross Agency Facility Flag                3542 non-null   object
 25  Condition Assessment Date                 3214 non-null   object
 26  Condition Assessment                      3214 non-null   float64
 27  Separate Asset Flag                       3542 non-null   object
 28  Notes                                     1288 non-null   object
 29  AddressComplete                           3542 non-null   object
 30  ReverseAddress                            728 non-null    object
dtypes: float64(10), object(21)
memory usage: 1014.5+ KB

Perform Some Remaining Cleanup Activities

In [94]:
#Replace values of NYC Boroughs to the NYC as a Whole.
# List of values to replace
replace_values = ["Bronx", "Queens", "Brooklyn", "Staten Island"]

# Replace those values with "New York, NY"
df['City'] = df['City'].replace(replace_values, "New York, NY")

In [97]:
#Update the zipcodes with less than five digits by adding leading zeroes.
df['ZIP Code'] = df['ZIP Code'].apply(lambda x: x.zfill(5))

In [101]:
#drop columns we will not be using
df.drop(['Secondary Modes Served','Street Address','Non-Agency Mode Served','Private Modes Served','Number of Parking Spaces','Notes'],axis=1, inplace=True)

In [103]:
# Create a new column 'Final Address' that contains the merged information from AddressComplete and ReverseAddress
df['Final Address'] = df.apply(
    lambda row: row['ReverseAddress'] if row['AddressComplete'] == "NA, NA, NA, NA" else row['AddressComplete'],
    axis=1
)

Print out the final cleaned data product

In [104]:
#download the file for further inspection
df.to_csv("stations_clean_final.csv")

In [105]:
#download the file for further inspection
files.download("stations_clean_final.csv")